<script src="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.js"></script>
<script src="{{ URL::asset('main-website/js/jquery.js') }}"></script>
<script src="{{ URL::asset('main-website/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/bootstrap-select.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/isotope.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.bootstrap-touchspin.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.countdown.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.countTo.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.easing.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.enllax.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.fancybox.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.mixitup.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.paroller.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.polyglot.language.switcher.js') }}"></script>
<script src="{{ URL::asset('main-website/js/map-script.js') }}"></script>
<script src="{{ URL::asset('main-website/js/nouislider.js') }}"></script>
<script src="{{ URL::asset('main-website/js/owl.js') }}"></script>
<script src="{{ URL::asset('main-website/js/timePicker.js') }}"></script>
<script src="{{ URL::asset('main-website/js/validation.js') }}"></script>
<script src="{{ URL::asset('main-website/js/wow.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/slick.js') }}"></script>
<script src="{{ URL::asset('main-website/js/lazyload.js') }}"></script>
<script src="{{ URL::asset('main-website/js/scrollbar.js') }}"></script>
<script src="{{ URL::asset('main-website/js/tilt.jquery.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.bxslider.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery-ui.js') }}"></script>
<script src="{{ URL::asset('main-website/js/parallax.min.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jquery.tinyscrollbar.js') }}"></script>
<script src="{{ URL::asset('main-website/js/jQuery.style.switcher.min.js') }}"></script>
<!-- thm custom script -->
<script src="{{ URL::asset('main-website/js/custom.js') }}"></script>

